### ISSUE TITLE
503 error running image through example site

### ISSUE THREAD

**Issue by forstmeier** [otiai10/gosseract#189]
# Summary

- Trying to submit a JPG file on the example website results in a 503 message in the output field

# Reproducibility

## Reproducibility Frequency

- 100%

Otherwise, describe how to reproduce

1. Take picture of text on a notepad (attached)
2. Upload to test website
3. Hit "Submit"
4. 503 error returned in output field

![test](https://user-images.githubusercontent.com/13358530/73612358-06964880-45b9-11ea-8dd7-f92f73c81877.jpg)

**Comment by otiai10** [comment]
I guess you meant this site https://ocr-example.herokuapp.com/,
and tried with your picture.

I got 503 as well, but 200 with smaller-resized image.
It seems because it's using a small tier of heroku instance which easily hits OOM.

**Conclusion:** Don't use huge pictures with the example site, otherwise you should setup [this server package](https://github.com/otiai10/ocrserver) on your huge instance.

**FYI:** I don't think `gosseract` can detect your hand-written characters very well. Here is the output I've got with your picture.

![image](https://user-images.githubusercontent.com/931554/73622235-3eb28f80-467c-11ea-9dac-a31a04c48cd0.png)

**Comment by forstmeier** [comment]
@otiai10 That answers the question perfectly - thanks!
